language: objective-c
osx_image: xcode10
cache:
  directories:
  - Carthage
before_install:
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.29.0/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
- sudo installer -pkg CartfileDiff.pkg -target /
- gem install xcpretty
install: true
script:
- set -o pipefail
- scripts/bootstrap-if-needed.sh
- xcodebuild -project SwiftStarter.xcodeproj -scheme "SwiftStarter" -destination "name=iPhone
  XS" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty
notifications:
  slack:
    secure: "jGgKCwXgIHRfrj284SH4V+tza6zEU2nSm0+e4OohKyggGQxQprwWS5zwEJEZwZAEk/fNKWopp/pyLy2InFqq3MDb4NvZsZ/M77OWbkd0Aq6X40NrlCJS/Pxdfu3crbV8l4We5DhTznS3Apa5mkKNLdGRKlcrIeL2P590+eN41fplqasTDfOyl9+JzP6ds8oZVztg8Mcd4hxbdtwPQkctEgHy5gnDs4tTKQg47eyYM0fYeKcPL1hNDJm7IaJNKhaFUnJZfZDnWusyDgfZsFgCOnZ3gAsa6f8TVYqcMbblUCgNSD98HYWMCznkoo3IA9BHf9TwW68pbqZ6Fd8PQIfKwoY7opxM/W4bJ1XZvOx7DmrjC/yft2exqizCbCJBf/yIjB1FzWOlgZays87/KuVSHHz9jLn9XjoeIk0k6SiQkNJCewoCtJcd8qS3D8wkSqKdSHbq6e7l8t97mlUo8DW/N8XRqMwISg4RPDgFPqN7lW7clmR6BPHr+kpiTR1rH0pwPh5XR9dryrFHN8LJoWCZMC9XLO4jYI7PvWRqeQWOJWKDY+70qeFsYKrmj/Se6GZPrLvjtn1+DUceNHAzC0whkUsusXjYrjjUbhDU+VOwOIz5dclyxp4ZQlesMZhhtCxrLA5WIf8/Uwa+XX0eDQJ/X65LF1RSO5ZCcJ54AF0sEW8="
