language: objective-c
osx_image: xcode8
xcode_project: App.xcodeproj
xcode_scheme: App
xcode_sdk: iphonesimulator10.0
before_install:
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
- gem install xcpretty
before_script:
- carthage bootstrap --platform iOS
script:
- set -o pipefail
- xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK test | xcpretty -c
notifications:
  email:
    on_success: change
    on_failure: always
