language: objective-c
osx_image: xcode8.0
xcode_project: App.xcodeproj
xcode_scheme: App
xcode_sdk: iphonesimulator9.3
before_install:
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.16.2/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
before_script:
- carthage bootstrap --no-use-binaries --platform iOS
notifications:
  email:
    on_success: change
    on_failure: always
