language: objective-c
osx_image: xcode8.0
xcode_project: App.xcodeproj
xcode_scheme: App
xcode_sdk: iphonesimulator10.0
before_install:
- "brew update"
- "brew outdated carthage || brew upgrade carthage"
before_script:
- carthage bootstrap --no-use-binaries --platform iOS
notifications:
  email:
    on_success: change
    on_failure: always
