language: objective-c
osx_image: xcode7.1
xcode_project: App.xcodeproj
xcode_scheme: App
xcode_sdk: iphonesimulator9.1
before_install:
- brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap --platform iOS
