language: objective-c
osx_image: xcode8
xcode_project: App.xcodeproj
xcode_scheme: App
xcode_sdk: iphonesimulator10.0
before_install:
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
before_script:
- carthage bootstrap --platform iOS
notifications:
  email:
    on_success: change
    on_failure: always
