language: objective-c
osx_image: xcode8.2
xcode_project: App.xcodeproj
xcode_scheme: App
xcode_sdk: iphonesimulator10.1
before_install:
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18.1/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
- gem install xcpretty
before_script:
- carthage bootstrap --no-use-binaries --platform iOS
script:
- set -o pipefail
- xcodebuild -project App.xcodeproj -scheme App -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1' test | xcpretty
notifications:
  email:
    recipients:
      - sabrine.elbahri@3ie.fr
    on_success: change
    on_failure: always
