language: objective-c
osx_image: xcode10
cache:
  directories:
  - Carthage
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.29.0/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
  - gem install xcpretty
install: true
script:
  - set -o pipefail
  - scripts/bootstrap-if-needed.sh
  - xcodebuild -project SwiftStarter.xcodeproj -scheme "SwiftStarter" -destination "name=iPhone XS" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty
notifications:
  email:
    recipients:
      - sofiane.beors@3ie.fr
    on_success: change
    on_failure: always
  slack: '3ie:HzehICjZ0mN6Hct7rpjRUtka'
