default_platform(:ios)

platform :ios do
  desc "Submit a new Beta."

lane :"beta" do
    increment_build_number
    match(
        type: "development",
        readonly: true
    )
    gym(
        configuration: "Debug",
        scheme: "iOS-Starter2019",
        silent: false,
        clean: true,
        output_directory: "Build",
        output_name: "iOS-Starter2019.ipa",
        export_method: "development",
    )
    upload_to_testflight(skip_submission: true)
 end

lane :"release" do
    match(
        type: "appstore",
        readonly: true
    )
    gym(
        configuration: "Release",
        scheme: "iOS-Starter2019",
        silent: false,
        clean: true,
        output_directory: "Build",
        output_name: "iOS-Starter2019.ipa",
        export_method: "app-store"
    )
    deliver(
        skip_metadata: true,
        skip_screenshots: true,
        precheck_include_in_app_purchases: false
    )
 end
end
